// <auto-generated />
namespace RolnikowePole.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class ZmodyfilpwamoeRestrykcjinapoleNazwaPlikuObrazka : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ZmodyfilpwamoeRestrykcjinapoleNazwaPlikuObrazka));
        
        string IMigrationMetadata.Id
        {
            get { return "201810201944356_Zmodyfilpwamoe Restrykcji na pole NazwaPlikuObrazka!"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
